spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/testesdb   
        username: postgres
        password: BemVindo!
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        